### ISSUE TITLE
Unit tests build fails

### ISSUE THREAD

**Issue by evra** [dojo/cli-build-app#196]
**Bug**

`dojo build -m unit` fails with errors related to CSS processing.

Package Version: 4.0.2

**Code**

`dojo create app -n demo`
`dojo build -m unit`

**Expected behavior:**

Test bundle is compiled without errors

**Actual behavior:**

```
i cli-build-app: 4.0.2
i typescript: 2.6.2
√ hash: ea1ddad9611d1140f218
× errors: 7
‼ warnings: 0

errors:
./node_modules/css-loader?{"sourceMap":true,"importLoaders":1}!./node_modules/extract-text-webpack-plugin/dist/loader.js?{"omit":1,"remove":true}!./node_modules/style-loader!./node_modules/@dojo/we
bpack-contrib/css-module-decorator-loader!./node_modules/css-loader?{"modules":true,"sourceMap":true,"importLoaders":1,"localIdentName":"[name]__[local]__[hash:base64:5]"}!./node_modules/postcss-lo
ader/lib?{"ident":"postcss","plugins":[null,null]}!./node_modules/@dojo/widgets/common/styles/animations.m.css
Module build failed: Unknown word (5:1)

  3 | // load the styles
  4 | var content =
require("!!../../../webpack-contrib/css-module-decorator-loader/index.js!../../../../css-loader/index.js?{\"modules\":true,\"sourceMap\":true,\"importLoaders\":1,\"localIdentName\":\"[name]__[local
]__[hash:base64:5]\"}!../../../../postcss-loader/lib/index.js??postcss!./animations.m.css");
> 5 | if(typeof content === 'string') content = [[module.id, content, '']];
    | ^
  6 | // Prepare cssTransformation
  7 | var transform;
  8 |

Syntax Error: Unknown word (5:1)

  3 | // load the styles
  4 | var content =
require("!!../../../webpack-contrib/css-module-decorator-loader/index.js!../../../../css-loader/index.js?{\"modules\":true,\"sourceMap\":true,\"importLoaders\":1,\"localIdentName\":\"[name]__[local
]__[hash:base64:5]\"}!../../../../postcss-loader/lib/index.js??postcss!./animations.m.css");
> 5 | if(typeof content === 'string') content = [[module.id, content, '']];
    | ^
  6 | // Prepare cssTransformation
  7 | var transform;
  8 |

    at C:\Users\rachie\projects\experiments\dojo4\demo-build-test\demo-theme\node_modules\css-loader\lib\processCss.js:226:23
    at <anonymous>
    at runMicrotasksCallback (internal/process/next_tick.js:121:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
@ ./node_modules/@dojo/widgets/common/styles/animations.m.css 4:14-342
@ ./node_modules/@dojo/widgets/common/styles/animations.m.css.js
@ ./node_modules/@dojo/widgets/slide-pane/index.mjs
@ ./node_modules/@dojo/widgets/toolbar/index.mjs
@ ./tests/unit/widgets/Menu.ts
@ multi ./tests/unit/all ./tests/unit/App ./tests/unit/main ./tests/unit/widgets/About ./tests/unit/widgets/all ./tests/unit/widgets/Home ./tests/unit/widgets/Menu
./tests/unit/widgets/Profile,./node_modules/css-loader?{"sourceMap":true,"importLoaders":1}!./node_modules/extract-text-webpack-plugin/dist/loader.js?{"omit":1,"remove":true}!./node_modules/style-l
oader!./node_modules/@dojo/webpack-contrib/css-module-decorator-loader!./node_modules/css-loader?{"modules":true,"sourceMap":true,"importLoaders":1,"localIdentName":"[name]__[local]__[hash:base64:5
]"}!./node_modules/postcss-loader/lib?{"ident":"postcss","plugins":[null,null]}!./node_modules/@dojo/widgets/common/styles/base.m.css
Module build failed: Unknown word (5:1)

```

**Comment by agubler** [comment]
I believe this is now resolved.
